# RPG AI Configuration

# Server Settings
server:
  host: "0.0.0.0"
  port: 5555
  max_players: 8
  timeout: 0  # 0 = sem timeout (ilimitado), > 0 = timeout em segundos
  connection_timeout: 0  # 0 = sem timeout (ilimitado), > 0 = timeout em segundos
  player_name_timeout: 0  # 0 = sem timeout (ilimitado), > 0 = timeout em segundos

# AI Settings
ai:
  endpoint: "http://localhost:5001/v1/chat/completions"
  api_key: ""
  model: "kb-gpt-neo"
  max_tokens: 600
  temperature: 0.8
  max_context_messages: 15
  request_timeout: 0  # 0 = sem timeout (ilimitado), > 0 = timeout em segundos
  connection_timeout: 0  # 0 = sem timeout (ilimitado), > 0 = timeout em segundos

# Game Settings
game:
  session_timeout: 0  # 0 = sem timeout (ilimitado), > 0 = timeout em minutos
  max_history: 100
  auto_save_interval: 60  # seconds
  
# World Settings
world:
  default_location: "Taverna do Dragão Dourado"
  starting_scenario: "Uma noite tempestuosa na taverna. O vento uiva pelas janelas e a lareira crepita suavemente."
  
# Procedural Generation Settings
procedural:
  enabled: true
  max_locations_per_expansion: 5
  max_npcs_per_location: 4
  location_name_max_length: 50
  npc_name_max_length: 30
  generation_creativity: 0.8  # 0.0 = muito conservador, 1.0 = muito criativo
  world_expansion_chance: 0.3  # Chance de expansão automática por evento
  
# NPC Memory Settings
memory:
  enabled: true
  max_memory_size: 100  # Máximo de conversas por NPC
  memory_cleanup_interval: 24  # Horas entre limpezas automáticas
  emotional_state_tracking: true
  relationship_development: true
  topic_memory_enabled: true
  player_interaction_history: true
  
# Logging
logging:
  level: "INFO"
  file: "rpg_ai.log"
  max_size: "10MB"
  backup_count: 5
